# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ]
        ),
        migrations.CreateModel(
            name='ValidToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50)),
                ('validFor', models.ForeignKey('User', on_delete=models.CASCADE)),
                ('issued', models.DateTimeField(auto_now_add=True, blank=True)),
            ]
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_one', models.ForeignKey('User', related_name = 'adder', on_delete = models.CASCADE)),
                ('friend_two', models.ForeignKey('User', related_name = 'addee',  on_delete = models.CASCADE)),
                ('since', models.DateTimeField(auto_now_add=True, blank=True)),
            ]
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_from', models.ForeignKey('User', related_name = 'sender', on_delete = models.CASCADE)),
                ('message_to', models.ForeignKey('User', related_name = 'sendee',  on_delete = models.CASCADE)),
                ('sent', models.DateTimeField(auto_now_add=True, blank=True)),
                ('message_contents', models.CharField(max_length=1000)),
            ]
        ),
    ]



